config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages, except: [:index, :new]
#  resources :messages , only: [:create]
end

app/models/message.rb
class Message < ActiveRecord::Base
    # 名前は必須入力かつ20文字以内
    validates :name, length: {maximum:20}, presence: true
    # 内容は必須入力かつ2文字以上
    validates :body, length: {minimum:2, maximum:30}, presence: true
    # 年齢は0以上かつ150以下の数字
    validates :age, inclusion: {in: 0..150}, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  
  def index
    @message = Message.new
    @messages = Message.all
  end
  
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかったとき
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました"
      render 'index'
    end
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path, notice:'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  
  def set_message
    @message = Message.find(params[:id])
  end
  
  ## ここまで
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
    </div>
  </nav>
  <div class="container">
      <% if notice %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |fx| %>
    <% if @message.errors.present? %>
        <div class="alert alert-danger">
            <%= alert %>
            <ul>
                <% @message.errors.full_messages.each do |full_message| %>
                    <li>
                        <%= full_message %>
                    </li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="form-group">
        <%= label :message, :name, "名前：" %>
        <%= fx.text_field :name, class: "form-control", placeholder: "名前を入力してください" %>
    </div>
    <div class="form-group">
        <%= label :message, :age, "年齢：" %>
        <%= fx.text_field :age, class: "form-control", placeholder: "年齢を入力してください" %>
    </div>
    <div class="form-group">
        <%= label :message, :body, "内容：" %>
        <%= fx.text_area :body, class: "form-control", placeholder: "内容を入力してください" %>
    </div>
    <%= fx.submit class: "btn btn-lg btn-primary" %>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<% #部分テンプレート %>
<%= render 'form' %>
<br>

<div class="panel panel-default">
    <div class="panel-heading">
        メッセージ一覧
    </div>
    <div class="panel-body">
        <% @messages.reverse.each do |message| %>
            <span class="label label-info"><%= message.name %> (<%= message.age %>)</span>
            <%= link_to "[Edit]", edit_message_path(message) %>
            <%= link_to "[Delete]", message, method: :delete, date: {confirm: '削除してもよろしいですか？'} %>
            <br>
            <%= simple_format(message.body) %>
        <% end %>
    </div>
</div>